//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvanterTür
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnvanterTür()
        {
            this.Envanters = new HashSet<Envanter>();
        }
    
        public int id { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public string typeName { get; set; }
        public string turAdi { get; set; }
        public string kategoriKodu { get; set; }
        public string ortakKod { get; set; }
        public string bgys { get; set; }
        public string it { get; set; }
        public string kalite { get; set; }
        public string ilgiliBirim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envanter> Envanters { get; set; }
    }
}
