//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envanter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Envanter()
        {
            this.EnvanterDetays = new HashSet<EnvanterDetay>();
            this.EnvanterDosyas = new HashSet<EnvanterDosya>();
            this.EnvanterSKDisis = new HashSet<EnvanterSKDisi>();
            this.ServisKayits = new HashSet<ServisKayit>();
            this.Zimmets = new HashSet<Zimmet>();
        }
    
        public int id { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<int> turId { get; set; }
        public string kodu { get; set; }
        public string ilgiliBirim { get; set; }
        public string aciklama { get; set; }
        public string status { get; set; }
        public string kaydedenPersonel { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public Nullable<bool> zstatus { get; set; }
    
        public virtual EnvanterTür EnvanterTür { get; set; }
        public virtual VarlikKategori VarlikKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvanterDetay> EnvanterDetays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvanterDosya> EnvanterDosyas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvanterSKDisi> EnvanterSKDisis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisKayit> ServisKayits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zimmet> Zimmets { get; set; }
    }
}
