//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Zimmets = new HashSet<Zimmet>();
        }
    
        public int id { get; set; }
        public Nullable<int> konumId { get; set; }
        public Nullable<int> typ { get; set; }
        public string adSoyad { get; set; }
        public string birimAdi { get; set; }
        public string unvan { get; set; }
    
        public virtual Konum Konum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zimmet> Zimmets { get; set; }
    }
}
