//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurSiraNo
    {
        public int id { get; set; }
        public string kategoriKodu { get; set; }
        public Nullable<int> sonkullanilanNo { get; set; }
    }
}
